### ISSUE TITLE
Could optionally use stage-direction for un-semanticated <i> tags in Chapter 6

### ISSUE THREAD

**Issue by drgrigg** [The-King-of-Toasters/banjo-patterson_an-outback-marriage#3]
In the following:

```
[singing]
<p>“It’s a vilet from me”⁠—</p>
<p>(<i>spoken.</i>) “What you’ll have, there’s chops, steaks, and bacon and eggs”⁠—“Chops, please.”</p>
<p>(<i>singer continues.</i>) “Sainted mother’s”⁠—</p>
<p>(<i>spoken.</i>) “Tea or coffee”⁠—“Tea, please.”</p>
<p>(<i>singer finishes.</i>)⁠—“grave.”</p>
```

You could optionally qualify the `<i>` tags with: epub:type="z3998:stage-direction" here because that's almost what they are, as though this was a little piece of drama. I've had to do a fair bit of this in Clarissa, which is probably why I think of it. But it's not essential.

**Comment by The-King-of-Toasters** [comment]
Yeah, I actually put them in at first, but took them out because it didn't seem right for a novel.
